### ISSUE TITLE
Non-English Gherkin files cause an "invalid file contents are produced" error

### ISSUE THREAD

**Issue by rayjolt** [ducminh-phan/reformat-gherkin#15]
When I run reformat-gherkin on a Gherkin file containing the following, I get the error message "INTERNAL ERROR: Invalid file contents are produced".

```
# language: de

@tag
Funktionalität: Feature name

    Szenario: Scenario name
        Angenommen foo
        Wenn bar
        Dann baz
```

Here is the command I ran, plus the full output.

```
$ reformat-gherkin .
Error: cannot format /home/jack/projects/python/test-reformat-gherkin/test.feature: INTERNAL ERROR: Invalid file contents are produced:
Parser errors:
(2:1): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Funktionalität: Feature name'
(4:3): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Szenario: Scenario name'
(5:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Angenommen foo'
(6:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Wenn bar'
(7:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Dann baz'
(8:0): unexpected end of file, expected: #TagLine, #FeatureLine, #Comment, #Empty
Please report a bug on https://github.com/ducminh-phan/reformat-gherkin/issues.
This invalid output might be helpful:
/tmp/rfmt-ghk_dk_hilnm.log

All done! 💥 💔 💥
1 file failed to reformat.

```

And here is the contents of /tmp/rfmt-ghk_dk_hilnm.log:

```
  File "/home/jack/.pyenv/versions/3.7.4/envs/test-reformat-gherkin/lib/python3.7/site-packages/reformat_gherkin/core.py", line 130, in assert_equivalent
    dst_ast = parse(dst)
  File "/home/jack/.pyenv/versions/3.7.4/envs/test-reformat-gherkin/lib/python3.7/site-packages/reformat_gherkin/parser.py", line 53, in parse
    raise InvalidInput(e) from e
@tag1
Funktionalität: Feature name

  Szenario: Scenario name
    Angenommen foo
    Wenn bar
    Dann baz
```

reformat-gherkin version: 1.0.0
Python version: 3.7.4

It looks like the problem is caused by reformat-gherkin failing to add the `# language: de` comment back to the file, which causes Gherkin to not recognise the German keywords when it tries to parse the reformatted file.

**Comment by rayjolt** [comment]
I would like to have a try at fixing this, although after looking through the code, the fix might be slightly tricky. This is because the language attribute is contained in the Feature AST node, but if there are any tags or comments before the feature line in the Gherkin file, then the corresponding Tag and Comment nodes come before the Feature node in `refactor_gherkin.formatter.LineFormatter.__nodes`. This means that we can't just add a Feature visitor to the LineFormatter class, as it doesn't guarantee that the language comment will be added to the start of the file.

My idea is to add a Comment node to the beginning of __nodes if the Feature language is not English. Does this seem like a reasonable way of doing this, or is there a better way?

**Comment by ducminh-phan** [comment]
@rayjolt Thank you for pointing out this issue. I came up with the same idea as yours to fix the issue after investigating. It would be great if you can contribute a patch.

However, if we only add a comment node if the language is not English, the header `# language: en` will be removed even if it appears in the feature file. Since Cucumber default to English, I think it's fine to remove the language header is such cases.

**Comment by rayjolt** [comment]
I don't think there's any way to tell whether a feature file has a `# language: en` comment from the AST that gherkin.parser.Parser produces. The comment isn't preserved in the comments list, only as a "language" key in the Feature node. So for English feature files, we can only choose whether to add the language header every time or to never add it. I'd say that never adding it is probably the more natural thing to do.

**Comment by ducminh-phan** [comment]
Agree. So let's not adding the language header if the language is English.

**Comment by rayjolt** [comment]
By the way, when we do add a language header, do you think it should be followed by an empty line? I think it looks better to have an empty line afterwards, but I am open to persuasion.

**Comment by ducminh-phan** [comment]
I think so. An empty line after the language header makes the file look better.
