### ISSUE TITLE
On Windows, reformatting a file larger than 32 KB causes a "path too long for Windows" error

### ISSUE THREAD

**Issue by rayjolt** [ducminh-phan/reformat-gherkin#34]
On Windows, trying to reformat a file longer than 32 KB fails with the error "stat: path too long for Windows".

## Steps to reproduce

1. Download [test.txt](https://github.com/ducminh-phan/reformat-gherkin/files/4364772/test.txt) (size: 34 KB)
2. Run reformat-gherkin on it with `reformat-gherkin test.txt`

## Expected result

The file is reformatted

## Actual result

The following error occurs:

```
Error: cannot format C:\path\to\test.txt: stat: path too long for Windows
All done! \U0001f4a5 \U0001f494 \U0001f4a5
1 file failed to reformat.
```

## Environment

reformat-gherkin 1.1.0
Python 3.7.3 (32-bit)
Windows 10

**Comment by rayjolt** [comment]
I tracked this down to the [Gherkin TokenScanner implementation](https://github.com/cucumber/cucumber/blob/aea94e0de737aa93dee7414efce8af50f6713ac2/gherkin/python/gherkin/token_scanner.py#L21). When you pass a string to Gherkin's Parser.parse, a TokenScanner instance is created, and on creation it checks to see if that string is a path on the filesystem using `os.path.exists()`. If the path exists, then Gherkin parses the contents of that file; if not, it parses the original string.

The problem is that [many Windows API functions have a maximum length of 32,767 characters](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation), so if a feature file is longer than that limit, then Windows will throw an error when trying to use it as a path in `os.path.exists()`.

Ideally this would be fixed in Gherkin itself, but judging from my last bug report there that will take time - someone needs to volunteer to maintain the Python Gherkin fork and get all the tests to pass again before they will release a new version. As a workaround we can pass paths to Parser.parse() instead of feature file contents.

**Comment by ducminh-phan** [comment]
Passing paths to `Parser.parse()` is not feasible since we need to make sure that we have an equivalent AST after formatting.

To work around the issue, we can subclass `TokenScanner` to handle strings only, then pass it to `Parser.parse()`.

**Comment by rayjolt** [comment]
Yes, that sounds like a good workaround until it can be fixed upstream.

**Comment by ducminh-phan** [comment]
@rayjolt Can you work on the issue? I don't have access to a Windows computer at the moment, so there's no way to reproduce and test but relying on Azure pipelines.

**Comment by rayjolt** [comment]
Sure, I'll have a look at it over the weekend.
