### ISSUE TITLE
Add a CONTRIBUTING file

### ISSUE THREAD

**Issue by rayjolt** [ducminh-phan/reformat-gherkin#36]
It would be good to add a CONTRIBUTING file for other people who are interested in contributing the project. This would help people avoid my mistake of basing my first pull request against master instead of against develop. :)

It would also be good to separate the installation instructions for users from the installation instructions for developers. Having the installation instructions for users in the README, and installation instructions for developers in CONTRIBUTING, would make it easier for users to understand how to use the software.

**Comment by ducminh-phan** [comment]
Thank you for your suggestion. I'm also thinking of setting up a Homebrew formula. Do you think it's necessary, or installing with pip or pre-commit is good enough?

**Comment by rayjolt** [comment]
I don't have a Mac, so Homebrew isn't important for me. I think starting with just pip and pre-commit is good enough - we can always add other methods later.
