### ISSUE TITLE
Option to not combine all tags

### ISSUE THREAD

**Issue by Frame42** [ducminh-phan/reformat-gherkin#43]
**Is your feature request related to a problem? Please describe.**
We use a lot of tags to classify our scenarios. I feel like it is more readable if the tags are not all grouped in one line, but rather grouped by root tags. 

**Describe the solution you'd like**
I would love a switch/config setting to prevent merging all tags on one line and leaving them over multiple contiguous lines

**Current behavior**
Input
```
  @testset.A @testset.B @testset.C @testset.Final
  @testtype.functional
  @jira.PEE-274
  Scenario: ADC Power
    ...
```
Output
```
  @testset.A @testset.B @testset.C @testset.Final @testtype.functional @jira.PEE-274
  Scenario: ADC Power
    ...
```

**Comment by ducminh-phan** [comment]
Hello @Frame42 

I think you can use the multi-line tags feature by adding the flag `--multi-line-tags` for the CLI, or adding `single_line_tags: False` to the `.reformat-gherkin.yaml` config file.

The rationale for the default behaviour of single-line tags is in issue #22.
