### ISSUE TITLE
Travis CI secrets need rotating according to recent security bulletin

### ISSUE THREAD

**Issue by rayjolt** [ducminh-phan/reformat-gherkin#47]
There was a bug in Travis CI where users filing pull requests from a forked repository could view secrets from the original repository. It's probably a good idea to rotate the Travis secrets for this repo.

Travis CI security bulletin: https://travis-ci.community/t/security-bulletin/12081

Feel free to close this issue if this is not applicable.

**Comment by ducminh-phan** [comment]
@rayjolt Thank you for notifying me! I was not aware of this issue. Travis CI secrets are updated accordingly.
