### ISSUE TITLE
with cattrs==22.2.0, fails to parse gherkin tables

### ISSUE THREAD

**Issue by dong-brian** [ducminh-phan/reformat-gherkin#59]
## Describe the bug

A new version of `cattrs` `22.2.0` was just published to PyPi.

As a result, new installations of `reformat-gherkin`, will fail to parse tables in feature files with errors such as:

ClassValidationError: While structuring GherkinDocument (1 sub-exception)

and sometimes even go as far as to reformat the file *but without the tables*.  This happens for both step data tables and example tables in scenario outlines.

We are using v3.0.0.

Config file:
```
check: false
alignment: left
tab_width: 2
```

### Steps to reproduce the behaviour

1. New pyenv installation of `reformat-gherkin`
2. Create a feature file with a table
3. Attempt to reformat the table
4. See ClassValidationError, reformat fails

### Expected behaviour

Successfully reformat Gherkin feature files containing tables

### Actual behaviour

Gherkin feature files containing tables either:
* raise ClassValidationError
* reformat the file without tables

### Environment

- reformat-gherkin v3.0.0
- Python 3.10.6
- MacOS 12.6

### Additional context

Seems like a breaking change in the latest cattrs

reformat-gherkin was working fine before this morning

**Comment by ducminh-phan** [comment]
Just released v3.0.1 as a hotfix for `cattrs`' breaking changes. I will look into upgrading `cattrs` to 22.2.0 in v3.1.0.
