### ISSUE TITLE
Make this a Mason package

### ISSUE THREAD

**Issue by conradogarciaberrotaran** [ducminh-phan/reformat-gherkin#68]
Hi everyone, thank you for this amazing tool. I've been using it for a couple of years now.
I want to include it in my neovim setup, which right now is using Mason as a package manager. I have ruff, black, isort, etc and I'm missing reformat-gherkin to format on save, that would be amazing.

If you're not familiar with Mason, please check this link: https://github.com/williamboman/mason.nvim.
The process of adding it in mason seems to be simple, it's explained here: https://github.com/mason-org/mason-registry?tab=readme-ov-file.
Contributing file seems clear enough: https://github.com/mason-org/mason-registry/blob/main/CONTRIBUTING.md

I wanted to get your approval given than some information for licenses and whatnot are up to you.

What do you think?

**Comment by conradogarciaberrotaran** [comment]
For good measure, black's file is here:
https://github.com/mason-org/mason-registry/blob/main/packages/black/package.yaml

**Comment by Zeioth** [comment]
@conradogarciaberrotaran Maybe this issue can be closed? I can install reformat-gherkin on mason successfully (and currently I'm PR none-ls to support it).

**Comment by conradogarciaberrotaran** [comment]
Closing it.
I'll check your none-ls PR if it's possible, I couldn't find a way to run reformat-gherkin on nvim.

**Comment by Zeioth** [comment]
@conradogarciaberrotaran check https://github.com/nvimtools/none-ls.nvim/pull/123
